import type { FifaMatch } from "./types";

// Bundled fallback used when BALLDONTLIE_API_KEY is unset or the API call fails,
// so the dashboard is demonstrable without a key. Plausible 2026 fixtures across
// the US/Canada/Mexico host venues — not official scheduling.

const GROUP_STAGE = { id: 1, name: "Group Stage", order: 1 };
const SEASON = { id: 1, year: 2026 };

export const SAMPLE_MATCHES: FifaMatch[] = [
  {
    id: 1,
    match_number: 1,
    datetime: "2026-06-11T19:00:00Z",
    status: "completed",
    clock_display: null,
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 1, name: "A" },
    stadium: { id: 1, name: "Estadio Azteca", city: "Mexico City", country: "MX" },
    home_team: { id: 1, name: "Mexico", abbreviation: "MEX", country_code: "MX", confederation: "CONCACAF" },
    away_team: { id: 2, name: "Croatia", abbreviation: "CRO", country_code: "HR", confederation: "UEFA" },
    home_score: 2,
    away_score: 1,
    home_score_penalties: null,
    away_score_penalties: null,
  },
  {
    id: 2,
    match_number: 2,
    datetime: "2026-06-12T16:00:00Z",
    status: "completed",
    clock_display: null,
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 2, name: "B" },
    stadium: { id: 2, name: "BMO Field", city: "Toronto", country: "CA" },
    home_team: { id: 3, name: "Canada", abbreviation: "CAN", country_code: "CA", confederation: "CONCACAF" },
    away_team: { id: 4, name: "Belgium", abbreviation: "BEL", country_code: "BE", confederation: "UEFA" },
    home_score: 1,
    away_score: 1,
    home_score_penalties: null,
    away_score_penalties: null,
  },
  {
    id: 3,
    match_number: 3,
    datetime: "2026-06-12T20:00:00Z",
    status: "in_progress",
    clock_display: "67'",
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 4, name: "D" },
    stadium: { id: 3, name: "MetLife Stadium", city: "East Rutherford", country: "US" },
    home_team: { id: 5, name: "United States", abbreviation: "USA", country_code: "US", confederation: "CONCACAF" },
    away_team: { id: 6, name: "Wales", abbreviation: "WAL", country_code: "GB", confederation: "UEFA" },
    home_score: 1,
    away_score: 0,
    home_score_penalties: null,
    away_score_penalties: null,
  },
  {
    id: 4,
    match_number: 4,
    datetime: "2026-06-13T18:00:00Z",
    status: "scheduled",
    clock_display: null,
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 5, name: "E" },
    stadium: { id: 4, name: "SoFi Stadium", city: "Los Angeles", country: "US" },
    home_team: { id: 7, name: "England", abbreviation: "ENG", country_code: "GB", confederation: "UEFA" },
    away_team: { id: 8, name: "Senegal", abbreviation: "SEN", country_code: "SN", confederation: "CAF" },
    home_score: null,
    away_score: null,
    home_score_penalties: null,
    away_score_penalties: null,
  },
  {
    id: 5,
    match_number: 5,
    datetime: "2026-06-13T21:00:00Z",
    status: "scheduled",
    clock_display: null,
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 6, name: "F" },
    stadium: { id: 5, name: "AT&T Stadium", city: "Arlington", country: "US" },
    home_team: { id: 9, name: "France", abbreviation: "FRA", country_code: "FR", confederation: "UEFA" },
    away_team: { id: 10, name: "Japan", abbreviation: "JPN", country_code: "JP", confederation: "AFC" },
    home_score: null,
    away_score: null,
    home_score_penalties: null,
    away_score_penalties: null,
  },
  {
    id: 6,
    match_number: 6,
    datetime: "2026-06-14T19:00:00Z",
    status: "scheduled",
    clock_display: null,
    season: SEASON,
    stage: GROUP_STAGE,
    group: { id: 8, name: "H" },
    stadium: { id: 6, name: "Hard Rock Stadium", city: "Miami", country: "US" },
    home_team: { id: 11, name: "Spain", abbreviation: "ESP", country_code: "ES", confederation: "UEFA" },
    away_team: { id: 12, name: "Morocco", abbreviation: "MAR", country_code: "MA", confederation: "CAF" },
    home_score: null,
    away_score: null,
    home_score_penalties: null,
    away_score_penalties: null,
  },
];
